### ISSUE TITLE
Colon in headings

### ISSUE THREAD

**Issue by waldo1001** [microsoft/alguidelines#103]
### Discussed in https://github.com/microsoft/alguidelines/discussions/102

<div type='discussions-op-text'>

<sup>Originally posted by **christianbraeunlich** February  5, 2022</sup>
At the end of the headings these colons seem unnecessary - just by the graphic design of the heading. Therefore, I would suggest removing the colons from the headings. This affects the template for the BC Patterns and the already published BC Patterns. Or could someone enlighten me what the colon is all about in these places? Thanks in advance! 😊

![grafik](https://user-images.githubusercontent.com/25108568/152656866-1bcd2c43-cf8c-451c-86d4-6179842554a0.png)
</div>

**Comment by christianbraeunlich** [comment]
Can be closed as #104 is merged.
