### ISSUE TITLE
Citing the ALGuidelines initiative

### ISSUE THREAD

**Issue by christianbraeunlich** [microsoft/alguidelines#148]
One of my friends told me he'd like to choose something like **clean code** for his thesis topic.

With that being said, I think it would be a good idea to provide a **CITATION.cff** in this repo.

![grafik](https://user-images.githubusercontent.com/25108568/158075652-624fcd31-9f88-45a0-9b56-2bca084e9590.png)

Related links:
- https://github.blog/2021-08-19-enhanced-support-citations-github/
- https://github.com/citation-file-format/citation-file-format

**Comment by JeremyVyska** [comment]
Merge approved and publishing now
