### ISSUE TITLE
Hard-coded string values in AL

### ISSUE THREAD

**Issue by PeterConijn** [microsoft/alguidelines#245]
This is based on a PR I reviewed for the BaseApp. It uses a lot of hard-coded values in (in this case) JSON message retrieval, e.g.

```AL
CallStack := GetJsonKeyValue(JObject, 'callStack');
```

Personally, hard-coded values make me twitch. More importantly, I think that in many cases, they are impractical from a maintenance standpoint. My preference would be to use locked labels with the -Tok suffix. This allows you to re-use tag names (if needed) and it allows you to group tag names together in the variables section.

```AL
procedure DoJsonStuff()
var
    CallStackTok: Label 'callStack', Locked = true;
begin
    // Awesome code...
    CallStack := GetJsonKeyValue(JObject, CallStackTok);
    // Mode awesome code
end;
```

What is the overall view about this. If we can get agreement, I will make a PR with a contribution.

**Comment by TheDoubleH** [comment]
> Personally, hard-coded values make me twitch. More importantly, I think that in many cases, they are impractical from a maintenance standpoint. My preference would be to use locked labels with the -Tok suffix. This allows you to re-use tag names (if needed) and it allows you to group tag names together in the variables section.

I agree - However, to me, there are times where it makes sense. In this instance I don't see the text as **Hardcoded**, but more like a field name.

I think the added overhead of labels, would make it less readable.

**Comment by ajkauffmann** [comment]
In my opinion, it's not a bad practice to use hardcoded key names. My first thought when reading this issue was the same as @TheDoubleH : they are like field names, just with single quotes around them (where we are used to double quotes for field names).

Usually, there is not so much maintenance when it comes to key names anyway. And when the same key name is used multiple times, I would rather write a function for it, like GetCustomerName() so the key name is only used one time. Storing the key name in a locked label doesn't solve any problem. It rather makes it less readable.

**Comment by waldo1001** [comment]
A

> I fully support @TheDoubleH and @ajkauffmann on this matter. There is nothing wrong with hardcoded values under certain conditions. Working with JSON is a good example of when, in my opinion, using hardcoding is justified and even improves readability.

Agree!

**Comment by pri-kise** [comment]
I don't have a problem with hardcoded values in general.
But when you work with a json as a temporary buffer and write the values into this buffer and read from this buffer later then I'd vote for the usage of Labels/Tokens. The simple reason: I don't want to keep the keys always in sync.

I know that runtime problems can be avoid by a simple write/read test.
I still vote against hard coded values in this case.

You can even see this pattern in the BaseApp.
e.g. check out the BackgroundTask Codeunits for the Cue Calculations. There they return the tokens in procedures that they can use the same key for the json buffer when the read the json document later.

**Comment by PeterConijn** [comment]
Thanks for the feedback. I have closed the PR.
