### ISSUE TITLE
[Hugo] set up docker environment

### ISSUE THREAD

**Issue by christianbraeunlich** [microsoft/alguidelines#53]
For a better reviewing of how the documentation would look like in the production environment it would be awesome if there's an additional subsection "Set up local environment" or "Containerization" in the Contributing section.

EDIT:
Just to give you an example on how this could look like:
<img width="960" alt="example-local-env" src="https://user-images.githubusercontent.com/25108568/144748037-f4ee7150-8798-41f3-8d6c-9fbece3ea742.png">

**Comment by TheDoubleH** [comment]
using docker just for hugo, seems a little overkill for me, but to each his own.

I just have hugo installed locally on my windows 11 laptop.

That said, it was my plan to include a section on the site showing how to do that.

**Comment by christianbraeunlich** [comment]
This would be great because I would like to use the LiveReload feature, which I haven't been able to get it working in the Docker container. Without the LiveReload feature working properly this docker introduction would be pointless. I changed the title to be a bit more precise here ;-)

**Comment by waldo1001** [comment]
I'm looking forward on such a description ;-)

**Comment by christianbraeunlich** [comment]
As already mentioned in https://github.com/microsoft/alguidelines/pull/57#issuecomment-1030581498 this ticket can now be closed.
