### ISSUE TITLE
[Hugo] Including Taxonomies

### ISSUE THREAD

**Issue by christianbraeunlich** [microsoft/alguidelines#54]
We could think about using user-defined taxonomies which is supported by Hugo: https://gohugo.io/content-management/taxonomies/ as a good practice as we move on with this project.

Example:
![grafik](https://user-images.githubusercontent.com/25108568/144756641-7eca4672-e336-4dd4-9934-9e1711ecd8ac.png)

**Comment by waldo1001** [comment]
Absolutely makes sense - but we need to make sure it doesn't get a complete mess of similar tags (can I call them tags? ;-)).

Would there be some kind of "picklist"?

**Comment by christianbraeunlich** [comment]
Fair enough, that's obviously a very good point, because it has some impact on the review process. As I'm still somewhat inexperienced in using Hugo, I can only think of building a tool like in this repo https://github.com/lpar/hugoutil that would help us out with the tag/categories/... management.

**Comment by JeremyVyska** [comment]
We probably need to add tags here and there, but the new layout much more richly supports Taxonomies now.

Let me know if this looks closeable with the new tools available to us.  😄

**Comment by christianbraeunlich** [comment]
Looks very much like closing this issue. Great job Jeremy!
