### ISSUE TITLE
[NAVPatterns] Update Formatting

### ISSUE THREAD

**Issue by christianbraeunlich** [microsoft/alguidelines#55]
Most of the formatting is not up-to-date and sometimes users are not shown any subsections because the file is named `index.md` instead of `_index.md`.

As this project hopefully lasts for the future, I would suggest honoring its predecessors and adapting all chapters as closely as possible to the original.

I already started doing so as I'm also interested in each and every topic and I already found out that most of the linked resources aren't available anymore or the link is not directed to the right location.

Already started this process and hope to create a pull request soon (might take some time).

**Comment by JeremyVyska** [comment]
Accidental automagic closing of issue, but I suspect you're probably not done.  Reopening.

**Comment by christianbraeunlich** [comment]
As I slowly progess with this ticket I would like to ask whether it's a good idea to simply copy the tags from the original Design Patterns (https://community.dynamics.com/nav/w/designpatterns) or simply wait until we've come up with a solution for https://github.com/microsoft/alguidelines/issues/54

**Comment by waldo1001** [comment]
Well .. copying them makes sense, tbh ..
